name: Testing
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run:
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip3 install numpy
        python3 testing.py